# Generated by Django 4.2.5 on 2023-10-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(max_length=20, verbose_name='Телеграм id')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('nickname', models.CharField(max_length=30, null=True, verbose_name='Ник в телеграме')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='Время от')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='Время до')),
                ('bad_partners', models.ManyToManyField(blank=True, to='bot.member', verbose_name='Нерекомендуемые напарники')),
                ('good_partners', models.ManyToManyField(blank=True, to='bot.member', verbose_name='Рекомендуемые напарники')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('start_day', models.DateField(verbose_name='День начала проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='StudyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, unique=True, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Уровень обучения',
                'verbose_name_plural': 'Уровни обучения',
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.member')),
            ],
            options={
                'verbose_name': 'Руководитель проектов',
                'verbose_name_plural': 'Руководители проектов',
            },
            bases=('bot.member',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('call_start', models.TimeField(blank=True, null=True, verbose_name='Начало созвона')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Утверждена')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='bot.project', verbose_name='Проект')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curr_teams', to='bot.projectmanager', verbose_name='Руководитель проекта')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.member')),
                ('curr_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bot.team', verbose_name='Текущая команда')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='bot.studylevel', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
            bases=('bot.member',),
        ),
    ]
