# Generated by Django 4.2.5 on 2023-10-17 22:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pm_file',
            field=models.FileField(null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
        migrations.AddField(
            model_name='project',
            name='students_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
        migrations.CreateModel(
            name='VacantTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_start', models.TimeField(verbose_name='Начало созвона')),
                ('vacant_pos_num', models.PositiveIntegerField(verbose_name='Кол-во свободных мест')),
                ('applicants_num', models.PositiveIntegerField(verbose_name='Кол-во претендентов')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.project', verbose_name='Проект')),
            ],
        ),
    ]
