# Generated by Django 4.2.5 on 2023-10-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_project_pm_file_project_students_file_vacanttime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacanttime',
            options={'verbose_name': 'Вакантный промежуток времени', 'verbose_name_plural': 'Вакантные промежутки времени'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='member',
            name='time_to',
        ),
        migrations.RemoveField(
            model_name='vacanttime',
            name='applicants_num',
        ),
        migrations.RemoveField(
            model_name='vacanttime',
            name='vacant_pos_num',
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Время от'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Время до'),
        ),
        migrations.AddField(
            model_name='student',
            name='call_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bot.vacanttime', verbose_name='Желаемое время созвона'),
        ),
        migrations.AddField(
            model_name='vacanttime',
            name='pms',
            field=models.ManyToManyField(blank=True, related_name='call_times', to='bot.vacanttime', verbose_name='Руководители проектов'),
        ),
    ]
