# Generated by Django 4.2.5 on 2023-10-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_vacanttime_options_remove_member_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanttime',
            name='pms',
            field=models.ManyToManyField(blank=True, related_name='call_times', to='bot.projectmanager', verbose_name='Руководители проектов'),
        ),
    ]
