# Generated by Django 4.2.5 on 2023-10-18 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_vacanttime_pms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pm_file',
            field=models.FileField(null=True, upload_to='pms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='students_file',
            field=models.FileField(blank=True, null=True, upload_to='students/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
