# Generated by Django 4.2.5 on 2023-10-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_project_pm_file_alter_project_students_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chosen_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Выбранное время'),
        ),
    ]
