# Generated by Django 4.2.5 on 2023-10-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_student_chosen_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ник в телеграме'),
        ),
        migrations.AlterField(
            model_name='student',
            name='call_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bot.vacanttime', verbose_name='Выбранное время'),
        ),
        migrations.AlterField(
            model_name='student',
            name='chosen_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Желаемое время созвона'),
        ),
    ]
