# Generated by Django 4.2.5 on 2023-10-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_member_nickname_alter_student_call_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanttime',
            name='call_start',
            field=models.TimeField(unique=True, verbose_name='Начало созвона'),
        ),
    ]
